# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urnExpUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_urnExpWindow(object):
    def setupUi(self, urnExpWindow):
        urnExpWindow.setObjectName(_fromUtf8("urnExpWindow"))
        urnExpWindow.resize(683, 735)
        self.centralwidget = QtGui.QWidget(urnExpWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 20, 520, 650))
        self.stackedWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stackedWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.stackedWidget.setFrameShape(QtGui.QFrame.WinPanel)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page1_consent = QtGui.QWidget()
        self.page1_consent.setObjectName(_fromUtf8("page1_consent"))
        self.consentInfo = QtGui.QLabel(self.page1_consent)
        self.consentInfo.setGeometry(QtCore.QRect(30, 110, 451, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.consentInfo.setFont(font)
        self.consentInfo.setWordWrap(True)
        self.consentInfo.setObjectName(_fromUtf8("consentInfo"))
        self.consentBox = QtGui.QCheckBox(self.page1_consent)
        self.consentBox.setEnabled(True)
        self.consentBox.setGeometry(QtCore.QRect(30, 560, 471, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.consentBox.setFont(font)
        self.consentBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.consentBox.setCheckable(True)
        self.consentBox.setTristate(False)
        self.consentBox.setObjectName(_fromUtf8("consentBox"))
        self.consentConfirm = QtGui.QPushButton(self.page1_consent)
        self.consentConfirm.setGeometry(QtCore.QRect(210, 600, 100, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.consentConfirm.setFont(font)
        self.consentConfirm.setObjectName(_fromUtf8("consentConfirm"))
        self.label = QtGui.QLabel(self.page1_consent)
        self.label.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.consentInfo_2 = QtGui.QLabel(self.page1_consent)
        self.consentInfo_2.setGeometry(QtCore.QRect(30, 70, 451, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.consentInfo_2.setFont(font)
        self.consentInfo_2.setWordWrap(True)
        self.consentInfo_2.setObjectName(_fromUtf8("consentInfo_2"))
        self.consentInfo_3 = QtGui.QLabel(self.page1_consent)
        self.consentInfo_3.setGeometry(QtCore.QRect(30, 220, 451, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.consentInfo_3.setFont(font)
        self.consentInfo_3.setWordWrap(True)
        self.consentInfo_3.setObjectName(_fromUtf8("consentInfo_3"))
        self.consentInfo_4 = QtGui.QLabel(self.page1_consent)
        self.consentInfo_4.setGeometry(QtCore.QRect(30, 340, 451, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.consentInfo_4.setFont(font)
        self.consentInfo_4.setWordWrap(True)
        self.consentInfo_4.setObjectName(_fromUtf8("consentInfo_4"))
        self.stackedWidget.addWidget(self.page1_consent)
        self.page2_demog = QtGui.QWidget()
        self.page2_demog.setObjectName(_fromUtf8("page2_demog"))
        self.labelDemog = QtGui.QLabel(self.page2_demog)
        self.labelDemog.setGeometry(QtCore.QRect(40, 70, 461, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDemog.setFont(font)
        self.labelDemog.setObjectName(_fromUtf8("labelDemog"))
        self.demogConfirm = QtGui.QPushButton(self.page2_demog)
        self.demogConfirm.setGeometry(QtCore.QRect(210, 600, 100, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.demogConfirm.setFont(font)
        self.demogConfirm.setObjectName(_fromUtf8("demogConfirm"))
        self.UserEducation = QtGui.QWidget(self.page2_demog)
        self.UserEducation.setGeometry(QtCore.QRect(30, 320, 321, 61))
        self.UserEducation.setObjectName(_fromUtf8("UserEducation"))
        self.Education = QtGui.QComboBox(self.UserEducation)
        self.Education.setGeometry(QtCore.QRect(140, 20, 181, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.Education.setFont(font)
        self.Education.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Education.setObjectName(_fromUtf8("Education"))
        self.Education.addItem(_fromUtf8(""))
        self.Education.setItemText(0, _fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.labelEducation = QtGui.QLabel(self.UserEducation)
        self.labelEducation.setGeometry(QtCore.QRect(10, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelEducation.setFont(font)
        self.labelEducation.setObjectName(_fromUtf8("labelEducation"))
        self.UserGender = QtGui.QWidget(self.page2_demog)
        self.UserGender.setGeometry(QtCore.QRect(30, 220, 321, 80))
        self.UserGender.setObjectName(_fromUtf8("UserGender"))
        self.Male = QtGui.QRadioButton(self.UserGender)
        self.Male.setGeometry(QtCore.QRect(140, 10, 82, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Male.setFont(font)
        self.Male.setObjectName(_fromUtf8("Male"))
        self.Female = QtGui.QRadioButton(self.UserGender)
        self.Female.setGeometry(QtCore.QRect(140, 40, 82, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Female.setFont(font)
        self.Female.setObjectName(_fromUtf8("Female"))
        self.labelGender = QtGui.QLabel(self.UserGender)
        self.labelGender.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelGender.setFont(font)
        self.labelGender.setObjectName(_fromUtf8("labelGender"))
        self.UserAge = QtGui.QWidget(self.page2_demog)
        self.UserAge.setGeometry(QtCore.QRect(30, 130, 321, 61))
        self.UserAge.setObjectName(_fromUtf8("UserAge"))
        self.Age = QtGui.QSpinBox(self.UserAge)
        self.Age.setGeometry(QtCore.QRect(140, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Age.setFont(font)
        self.Age.setObjectName(_fromUtf8("Age"))
        self.labelAge = QtGui.QLabel(self.UserAge)
        self.labelAge.setGeometry(QtCore.QRect(10, 20, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAge.setFont(font)
        self.labelAge.setObjectName(_fromUtf8("labelAge"))
        self.labelErrorAge = QtGui.QLabel(self.page2_demog)
        self.labelErrorAge.setGeometry(QtCore.QRect(370, 130, 111, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorAge.setFont(font)
        self.labelErrorAge.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelErrorAge.setWordWrap(True)
        self.labelErrorAge.setObjectName(_fromUtf8("labelErrorAge"))
        self.labelErrorGender = QtGui.QLabel(self.page2_demog)
        self.labelErrorGender.setGeometry(QtCore.QRect(370, 220, 111, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorGender.setFont(font)
        self.labelErrorGender.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelErrorGender.setWordWrap(True)
        self.labelErrorGender.setObjectName(_fromUtf8("labelErrorGender"))
        self.labelErrorEducation = QtGui.QLabel(self.page2_demog)
        self.labelErrorEducation.setGeometry(QtCore.QRect(370, 330, 111, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorEducation.setFont(font)
        self.labelErrorEducation.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelErrorEducation.setWordWrap(True)
        self.labelErrorEducation.setObjectName(_fromUtf8("labelErrorEducation"))
        self.label_2 = QtGui.QLabel(self.page2_demog)
        self.label_2.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.stackedWidget.addWidget(self.page2_demog)
        self.page3_instructions = QtGui.QWidget()
        self.page3_instructions.setObjectName(_fromUtf8("page3_instructions"))
        self.labelInstructionHeading = QtGui.QLabel(self.page3_instructions)
        self.labelInstructionHeading.setGeometry(QtCore.QRect(40, 70, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.labelInstructionHeading.setFont(font)
        self.labelInstructionHeading.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelInstructionHeading.setLineWidth(0)
        self.labelInstructionHeading.setWordWrap(True)
        self.labelInstructionHeading.setObjectName(_fromUtf8("labelInstructionHeading"))
        self.instructionConfirm = QtGui.QPushButton(self.page3_instructions)
        self.instructionConfirm.setGeometry(QtCore.QRect(210, 600, 100, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.instructionConfirm.setFont(font)
        self.instructionConfirm.setObjectName(_fromUtf8("instructionConfirm"))
        self.labelExpInstructions = QtGui.QLabel(self.page3_instructions)
        self.labelExpInstructions.setGeometry(QtCore.QRect(40, 130, 441, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.labelExpInstructions.setFont(font)
        self.labelExpInstructions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelExpInstructions.setLineWidth(0)
        self.labelExpInstructions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelExpInstructions.setWordWrap(True)
        self.labelExpInstructions.setObjectName(_fromUtf8("labelExpInstructions"))
        self.labelExpInstructions_2 = QtGui.QLabel(self.page3_instructions)
        self.labelExpInstructions_2.setGeometry(QtCore.QRect(40, 200, 441, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.labelExpInstructions_2.setFont(font)
        self.labelExpInstructions_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelExpInstructions_2.setLineWidth(0)
        self.labelExpInstructions_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelExpInstructions_2.setWordWrap(True)
        self.labelExpInstructions_2.setObjectName(_fromUtf8("labelExpInstructions_2"))
        self.labelExpInstructions_3 = QtGui.QLabel(self.page3_instructions)
        self.labelExpInstructions_3.setGeometry(QtCore.QRect(40, 280, 441, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.labelExpInstructions_3.setFont(font)
        self.labelExpInstructions_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelExpInstructions_3.setLineWidth(0)
        self.labelExpInstructions_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelExpInstructions_3.setWordWrap(True)
        self.labelExpInstructions_3.setObjectName(_fromUtf8("labelExpInstructions_3"))
        self.labelExpInstructions_5 = QtGui.QLabel(self.page3_instructions)
        self.labelExpInstructions_5.setGeometry(QtCore.QRect(40, 430, 441, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.labelExpInstructions_5.setFont(font)
        self.labelExpInstructions_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelExpInstructions_5.setLineWidth(0)
        self.labelExpInstructions_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelExpInstructions_5.setWordWrap(True)
        self.labelExpInstructions_5.setObjectName(_fromUtf8("labelExpInstructions_5"))
        self.label_3 = QtGui.QLabel(self.page3_instructions)
        self.label_3.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.labelExpInstructions_4 = QtGui.QLabel(self.page3_instructions)
        self.labelExpInstructions_4.setGeometry(QtCore.QRect(40, 360, 441, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.labelExpInstructions_4.setFont(font)
        self.labelExpInstructions_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelExpInstructions_4.setLineWidth(0)
        self.labelExpInstructions_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelExpInstructions_4.setWordWrap(True)
        self.labelExpInstructions_4.setObjectName(_fromUtf8("labelExpInstructions_4"))
        self.instructionConfirm.raise_()
        self.labelExpInstructions.raise_()
        self.labelExpInstructions_2.raise_()
        self.labelExpInstructions_3.raise_()
        self.labelExpInstructions_5.raise_()
        self.label_3.raise_()
        self.labelInstructionHeading.raise_()
        self.labelExpInstructions_4.raise_()
        self.stackedWidget.addWidget(self.page3_instructions)
        self.page4_urnSelect = QtGui.QWidget()
        self.page4_urnSelect.setObjectName(_fromUtf8("page4_urnSelect"))
        self.urnConfirm = QtGui.QPushButton(self.page4_urnSelect)
        self.urnConfirm.setGeometry(QtCore.QRect(185, 600, 150, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.urnConfirm.setFont(font)
        self.urnConfirm.setObjectName(_fromUtf8("urnConfirm"))
        self.labelUrnA = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnA.setGeometry(QtCore.QRect(150, 100, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelUrnA.setFont(font)
        self.labelUrnA.setObjectName(_fromUtf8("labelUrnA"))
        self.labelUrnB = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnB.setGeometry(QtCore.QRect(340, 100, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelUrnB.setFont(font)
        self.labelUrnB.setObjectName(_fromUtf8("labelUrnB"))
        self.labelUrnHeading = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnHeading.setGeometry(QtCore.QRect(100, 60, 321, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelUrnHeading.setFont(font)
        self.labelUrnHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUrnHeading.setWordWrap(True)
        self.labelUrnHeading.setObjectName(_fromUtf8("labelUrnHeading"))
        self.labelUrnChoice = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnChoice.setGeometry(QtCore.QRect(140, 480, 241, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelUrnChoice.setFont(font)
        self.labelUrnChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUrnChoice.setWordWrap(True)
        self.labelUrnChoice.setObjectName(_fromUtf8("labelUrnChoice"))
        self.label_4 = QtGui.QLabel(self.page4_urnSelect)
        self.label_4.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.labelUrnAratio = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnAratio.setGeometry(QtCore.QRect(80, 370, 150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelUrnAratio.setFont(font)
        self.labelUrnAratio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUrnAratio.setWordWrap(True)
        self.labelUrnAratio.setObjectName(_fromUtf8("labelUrnAratio"))
        self.labelUrnBratio = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnBratio.setGeometry(QtCore.QRect(270, 370, 150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelUrnBratio.setFont(font)
        self.labelUrnBratio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUrnBratio.setWordWrap(True)
        self.labelUrnBratio.setObjectName(_fromUtf8("labelUrnBratio"))
        self.labelUrnError = QtGui.QLabel(self.page4_urnSelect)
        self.labelUrnError.setGeometry(QtCore.QRect(190, 430, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelUrnError.setFont(font)
        self.labelUrnError.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelUrnError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUrnError.setWordWrap(True)
        self.labelUrnError.setObjectName(_fromUtf8("labelUrnError"))
        self.urnConfirm.raise_()
        self.labelUrnA.raise_()
        self.labelUrnB.raise_()
        self.labelUrnChoice.raise_()
        self.labelUrnAratio.raise_()
        self.labelUrnBratio.raise_()
        self.label_4.raise_()
        self.labelUrnHeading.raise_()
        self.labelUrnError.raise_()
        self.stackedWidget.addWidget(self.page4_urnSelect)
        self.page5_handurn = QtGui.QWidget()
        self.page5_handurn.setObjectName(_fromUtf8("page5_handurn"))
        self.label_12 = QtGui.QLabel(self.page5_handurn)
        self.label_12.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.bigUrn = QtGui.QLabel(self.page5_handurn)
        self.bigUrn.setGeometry(QtCore.QRect(180, 230, 140, 231))
        self.bigUrn.setText(_fromUtf8(""))
        self.bigUrn.setPixmap(QtGui.QPixmap(_fromUtf8("urn.jpg")))
        self.bigUrn.setScaledContents(True)
        self.bigUrn.setObjectName(_fromUtf8("bigUrn"))
        self.hand = QtGui.QLabel(self.page5_handurn)
        self.hand.setGeometry(QtCore.QRect(210, 20, 71, 161))
        self.hand.setText(_fromUtf8(""))
        self.hand.setPixmap(QtGui.QPixmap(_fromUtf8("hand.jpg")))
        self.hand.setScaledContents(True)
        self.hand.setObjectName(_fromUtf8("hand"))
        self.hand.raise_()
        self.label_12.raise_()
        self.bigUrn.raise_()
        self.stackedWidget.addWidget(self.page5_handurn)
        self.page6_results = QtGui.QWidget()
        self.page6_results.setObjectName(_fromUtf8("page6_results"))
        self.labelMarbleChoice = QtGui.QLabel(self.page6_results)
        self.labelMarbleChoice.setGeometry(QtCore.QRect(130, 60, 260, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMarbleChoice.setFont(font)
        self.labelMarbleChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMarbleChoice.setWordWrap(True)
        self.labelMarbleChoice.setObjectName(_fromUtf8("labelMarbleChoice"))
        self.continueButton = QtGui.QPushButton(self.page6_results)
        self.continueButton.setGeometry(QtCore.QRect(210, 600, 100, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.continueButton.setFont(font)
        self.continueButton.setObjectName(_fromUtf8("continueButton"))
        self.blueMarble = QtGui.QLabel(self.page6_results)
        self.blueMarble.setGeometry(QtCore.QRect(185, 120, 150, 150))
        self.blueMarble.setText(_fromUtf8(""))
        self.blueMarble.setPixmap(QtGui.QPixmap(_fromUtf8("bluemarble.png")))
        self.blueMarble.setScaledContents(True)
        self.blueMarble.setObjectName(_fromUtf8("blueMarble"))
        self.redMarble = QtGui.QLabel(self.page6_results)
        self.redMarble.setGeometry(QtCore.QRect(185, 120, 150, 150))
        self.redMarble.setText(_fromUtf8(""))
        self.redMarble.setPixmap(QtGui.QPixmap(_fromUtf8("redmarble.jpg")))
        self.redMarble.setScaledContents(True)
        self.redMarble.setObjectName(_fromUtf8("redMarble"))
        self.labelPrize = QtGui.QLabel(self.page6_results)
        self.labelPrize.setGeometry(QtCore.QRect(100, 310, 320, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPrize.setFont(font)
        self.labelPrize.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrize.setWordWrap(True)
        self.labelPrize.setObjectName(_fromUtf8("labelPrize"))
        self.label_5 = QtGui.QLabel(self.page6_results)
        self.label_5.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.emailWidget = QtGui.QWidget(self.page6_results)
        self.emailWidget.setGeometry(QtCore.QRect(95, 430, 330, 91))
        self.emailWidget.setObjectName(_fromUtf8("emailWidget"))
        self.labelEmail = QtGui.QLabel(self.emailWidget)
        self.labelEmail.setGeometry(QtCore.QRect(10, -20, 321, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.labelEmail.setFont(font)
        self.labelEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEmail.setWordWrap(True)
        self.labelEmail.setObjectName(_fromUtf8("labelEmail"))
        self.inputEmail = QtGui.QLineEdit(self.emailWidget)
        self.inputEmail.setGeometry(QtCore.QRect(10, 60, 311, 21))
        self.inputEmail.setObjectName(_fromUtf8("inputEmail"))
        self.labelEmailError = QtGui.QLabel(self.page6_results)
        self.labelEmailError.setGeometry(QtCore.QRect(110, 520, 311, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelEmailError.setFont(font)
        self.labelEmailError.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelEmailError.setWordWrap(True)
        self.labelEmailError.setObjectName(_fromUtf8("labelEmailError"))
        self.redMarble.raise_()
        self.labelMarbleChoice.raise_()
        self.continueButton.raise_()
        self.blueMarble.raise_()
        self.labelPrize.raise_()
        self.label_5.raise_()
        self.emailWidget.raise_()
        self.labelEmailError.raise_()
        self.stackedWidget.addWidget(self.page6_results)
        self.page7_debrief = QtGui.QWidget()
        self.page7_debrief.setObjectName(_fromUtf8("page7_debrief"))
        self.label_6 = QtGui.QLabel(self.page7_debrief)
        self.label_6.setGeometry(QtCore.QRect(30, 440, 451, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.endButton = QtGui.QPushButton(self.page7_debrief)
        self.endButton.setGeometry(QtCore.QRect(210, 600, 100, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.endButton.setFont(font)
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.label_7 = QtGui.QLabel(self.page7_debrief)
        self.label_7.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.page7_debrief)
        self.label_8.setGeometry(QtCore.QRect(30, 80, 451, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.page7_debrief)
        self.label_9.setGeometry(QtCore.QRect(30, 230, 451, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.stackedWidget.addWidget(self.page7_debrief)
        urnExpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(urnExpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        urnExpWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(urnExpWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        urnExpWindow.setStatusBar(self.statusbar)

        self.retranslateUi(urnExpWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(urnExpWindow)

    def retranslateUi(self, urnExpWindow):
        urnExpWindow.setWindowTitle(_translate("urnExpWindow", "MainWindow", None))
        self.consentInfo.setText(_translate("urnExpWindow", "We would like to invite you to participate in this experiment directed by researchers at UCL. You should only participate if you want to; choosing not to take part will not disadvantage you in any way. Before you decide whether you want to take part, it is important for you to read the following information carefully and discuss it with others if you wish. Ask us if there is anything that is not clear or if you would like more information. ", None))
        self.consentBox.setText(_translate("urnExpWindow", "Tick this box to confirm you consent to participate in this experiment", None))
        self.consentConfirm.setText(_translate("urnExpWindow", "Continue", None))
        self.consentInfo_2.setText(_translate("urnExpWindow", "A replication of the Ellsberg Urns with Few Balls", None))
        self.consentInfo_3.setText(_translate("urnExpWindow", "In this study you will be asked to read a short description of a choice task and then choose your preferred option. Only UCL researchers working with Prof Jeremy Bentham will analyse these data. It is up to you to decide whether or not to take part. If you decide to take part you will be given this information sheet to keep and be asked to sign a consent form. If you decide to take part you are still free to withdraw at any time and without giving a reason. You may wish to print this information for your records.", None))
        self.consentInfo_4.setText(_translate("urnExpWindow", "By ticking the box below you agree that you have: \n"
" - read the information above \n"
" - had an opportunity to ask questions and discuss the study \n"
" - received satisfactory answers to all my questions or have been advised of an individual to contact \n"
" - understood that I have the right to withdraw at any stage simply by closing the experiment window\n"
" - understood that I consent to the processing of my personal information for the purposes of this study only and that any such information will be treated as strictly confidential and handled in accordance with the provisions of the Data Protection Act 1998 \n"
" - understood that, by clicking ‘Continue’, I consent to participate in this study ", None))
        self.labelDemog.setText(_translate("urnExpWindow", "Please enter some details about yourself and then click \'Continue\'", None))
        self.demogConfirm.setText(_translate("urnExpWindow", "Continue", None))
        self.Education.setItemText(1, _translate("urnExpWindow", "Upper Secondary", None))
        self.Education.setItemText(2, _translate("urnExpWindow", "Post-secondary", None))
        self.Education.setItemText(3, _translate("urnExpWindow", "Bachelor\'s or equivalent", None))
        self.Education.setItemText(4, _translate("urnExpWindow", "Master\'s or equivalent", None))
        self.Education.setItemText(5, _translate("urnExpWindow", "Doctoral or equivalent", None))
        self.labelEducation.setText(_translate("urnExpWindow", "Education Level", None))
        self.Male.setText(_translate("urnExpWindow", "Male", None))
        self.Female.setText(_translate("urnExpWindow", "Female", None))
        self.labelGender.setText(_translate("urnExpWindow", "Gender", None))
        self.labelAge.setText(_translate("urnExpWindow", "Age", None))
        self.labelErrorAge.setText(_translate("urnExpWindow", "You need to be over 18 to take part in this experiment", None))
        self.labelErrorGender.setText(_translate("urnExpWindow", "You must select your gender", None))
        self.labelErrorEducation.setText(_translate("urnExpWindow", "You must select your highest education level", None))
        self.labelInstructionHeading.setText(_translate("urnExpWindow", "Please consider the following problem carefully and then click \'Continue\'", None))
        self.instructionConfirm.setText(_translate("urnExpWindow", "Continue", None))
        self.labelExpInstructions.setText(_translate("urnExpWindow", "On the next screen there will be two urns, labeled A and B, containing red and blue marbles, and you have to draw a marble from one of the urns. If you get a blue marble, you will be entered into a £30 lottery draw. ", None))
        self.labelExpInstructions_2.setText(_translate("urnExpWindow", "Text from program....", None))
        self.labelExpInstructions_3.setText(_translate("urnExpWindow", "Text from program...", None))
        self.labelExpInstructions_5.setText(_translate("urnExpWindow", "You have to decide whether you prefer to draw a marble at random from Urn A or Urn B. What you hope is to draw a blue marble and be entered for the £30 lottery draw. Consider very carefully from which urn you prefer to draw the marble, then click on the urn you want to draw from.  After you have confirmed your urn choice, the computer will then randomly draw a marble from your chosen urn and show you the result.", None))
        self.labelExpInstructions_4.setText(_translate("urnExpWindow", "Text from program...", None))
        self.urnConfirm.setText(_translate("urnExpWindow", "Confirm", None))
        self.labelUrnA.setText(_translate("urnExpWindow", "A", None))
        self.labelUrnB.setText(_translate("urnExpWindow", "B", None))
        self.labelUrnHeading.setText(_translate("urnExpWindow", "Click the urn you want to draw a marble from and click \'Confirm\'", None))
        self.labelUrnChoice.setText(_translate("urnExpWindow", "You chose the urn with...", None))
        self.labelUrnAratio.setText(_translate("urnExpWindow", "urnA ratio", None))
        self.labelUrnBratio.setText(_translate("urnExpWindow", "urnB ratio", None))
        self.labelUrnError.setText(_translate("urnExpWindow", "Please choose an urn", None))
        self.labelMarbleChoice.setText(_translate("urnExpWindow", "Marble message", None))
        self.continueButton.setText(_translate("urnExpWindow", "Continue", None))
        self.labelPrize.setText(_translate("urnExpWindow", "Prize message", None))
        self.labelEmail.setText(_translate("urnExpWindow", "Please provide your email address in the box below so we can contact you if you win the lottery draw. Then click \'Continue\'", None))
        self.labelEmailError.setText(_translate("urnExpWindow", "Double check you have input a valid email address", None))
        self.label_6.setText(_translate("urnExpWindow", "Thanks again for taking part. You can now close the window or click \'End experiment\' below.", None))
        self.endButton.setText(_translate("urnExpWindow", "End experiment", None))
        self.label_8.setText(_translate("urnExpWindow", "Thank you for taking part in the experiment. \n"
" \n"
"This experiment attempts to replicate the design of a previous experiment by Pulford and Colman (2008). Their experiment asked participants to draw marbles from real urns to test whether the amiguity aversion effect persisted with different numbers of marbles in the urns. The ambiguity aversion effect, first discussed by Ellsberg (1961), is people’s tendency to prefer risky choices when the outcome is 50:50, against choices with unknown outcomes.   ", None))
        self.label_9.setText(_translate("urnExpWindow", "If you have further questions about this experiment please contact ucjujrm@ucl.ac.uk. And if you\'d like to know more about this topic, you can read the original papers: \n"
"\n"
"Ellsberg, D. (1961). Risk, ambiguity, and the Savage axioms. The quarterly journal of economics, 643-669.\n"
"\n"
"Pulford, B. D., & Colman, A. M. (2008). Size doesn\'t really matter: Ambiguity aversion in Ellsberg urns with few balls. Experimental Psychology, 55(1), 31-37. ", None))

